### ISSUE TITLE
Add basic README getting started

### ISSUE THREAD

**Issue by philips** [coreos/bootkube#16]
Lots of people want to play with this and are pinging @polvi's monokube repo: https://github.com/polvi/monokube/issues/2

People just need a quick getting started. We can mostly just port stuff from https://github.com/polvi/monokube#monokube

**Comment by philips** [comment]
@derekparker do you think you could take a swing at this?

**Comment by derekparker** [comment]
@philips absolutely.

**Comment by aaronlevy** [comment]
fixed in: https://github.com/coreos/bootkube/issues/16

Also, we do have some quick-hack instructions in: 
https://github.com/coreos/bootkube/tree/master/hack/single-node
https://github.com/coreos/bootkube/tree/master/hack/multi-node
