### ISSUE TITLE
Provide bootkube flags table with example arguments

### ISSUE THREAD

**Issue by dghubble** [coreos/bootkube#21]
`bootkube render` commands aren't directly discover-able just from using `--help`. I read through the hack examples and figured them out. A better way is to mention reasonable examples for each argument in the help output and/or to add a table with example valid arguments.

Should the IPs for SANS include IP1.=172.15.0.2,IP.2=10.3.0.1 or just the IPs (no)? What separator? The API server is specified by IP address. The etcd servers expect a scheme and port. Ideally users should not guess at or piece together the tool's argument assumptions.

**Comment by philips** [comment]
Right, we need an overall guide to how to use bootkube. Currently, I have no idea of where to start.

**Comment by aaronlevy** [comment]
More detailed usage information added in: https://github.com/coreos/bootkube/pull/36
We can track the overall guide work in: https://github.com/coreos/bootkube/issues/32
