### ISSUE TITLE
SSH Agent Support

### ISSUE THREAD

**Issue by dghubble** [coreos/bootkube#23]
The `bootkube start --ssh-keyfile` flag assumes a SSH key file is (1) available on disk and (2) not locked by a passphrase. It may be possible to do this in a more general way through the SSH Agent, possibly using https://godoc.org/golang.org/x/crypto/ssh/agent.

**Comment by philips** [comment]
@dghubble fleet has code for this @jonboulle likely knows where.

**Comment by aaronlevy** [comment]
The SSH tunnel code has been removed in favor of running bootkube "on-host"
