### ISSUE TITLE
Rendered kubeconfig.yaml uses wrong server value

### ISSUE THREAD

**Issue by dghubble** [coreos/bootkube#24]
The `kubeconfig.yaml` cluster server value is hardcoded to `https://172.17.4.100:6443` and I see a TODO comment. Adding this issue to track the fix. For now, I'll comment that users should edit the config manually.

https://github.com/coreos/bootkube/blob/master/pkg/asset/k8s.go#L51

**Comment by aaronlevy** [comment]
fixed in https://github.com/coreos/bootkube/pull/22
