### ISSUE TITLE
Allow an on-host mode of executing bootkube

### ISSUE THREAD

**Issue by aaronlevy** [coreos/bootkube#29]
This would allow for rendering assets likely directly to etcd, then running bootkube locally on a host (no ssh-tunnel) using those assets. The end result I'd probably like to see is something along the lines of:

`sudo rkt run quay.io/coreos/bootkube start --etcd=https://example.com:2379`

/cc @chancez @dghubble

**Comment by dghubble** [comment]
Maybe take an `etcd-path` as well so I can use a dedicated etcd cluster to bootstrap multiple different self-hosted Kubernetes clusters, possibly at the same time.

**Comment by aaronlevy** [comment]
Yeah, that would be a pretty interesting use-case.

One UX thing I'm not sure about is the render step. Right now it goes to disk as a means of being easily configurable (without trying to plumb through configuration / adding templates for everything).

So I could see something like:

```
rkt run quay.io/coreos/bootkube render --etcd-path=cluster/a
rkt run quay.io/coreos/bootkube start --etcd-path=cluster/a
```

But that means nothing is (easily) configurable from default templates.

**Comment by aaronlevy** [comment]
The on-host implementation was added in https://github.com/coreos/bootkube/pull/36

This just includes referencing local assets (not etcd paths). If we still want that we can open a new issue.
