### ISSUE TITLE
Flaky bring-up: apiserver fails

### ISSUE THREAD

**Issue by dghubble** [coreos/bootkube#49]
Most of the time `bootkube` reports that components have started and the cluster is accessible via `kubectl`. Occasionally, components are reported to be Running, but the `apiserver` container exits and does not restart. Reporting logs from a cluster where this occurred. Master node 172.15.0.21 is up.

apiserver Docker logs

```
I0606 20:35:39.439996       1 server.go:188] Will report 172.15.0.21 as public IP address.
I0606 20:35:39.440050       1 plugins.go:71] No cloud provider specified.
I0606 20:35:39.440103       1 server.go:112] constructing etcd storage interface.
  sv: v1
  mv: __internal
I0606 20:35:39.440146       1 genericapiserver.go:82] Adding storage destination for group 
I0606 20:35:39.440152       1 server.go:296] Configuring extensions/v1beta1 storage destination
I0606 20:35:39.440156       1 server.go:112] constructing etcd storage interface.
  sv: extensions/v1beta1
  mv: extensions/__internal
I0606 20:35:39.440176       1 genericapiserver.go:82] Adding storage destination for group extensions
I0606 20:35:39.440179       1 genericapiserver.go:82] Adding storage destination for group autoscaling
I0606 20:35:39.440182       1 genericapiserver.go:82] Adding storage destination for group batch
I0606 20:35:39.440186       1 server.go:325] Configuring autoscaling/v1 storage destination
I0606 20:35:39.440190       1 server.go:339] Using autoscaling/v1 for autoscaling group storage version
I0606 20:35:39.440193       1 server.go:112] constructing etcd storage interface.
  sv: autoscaling/v1
  mv: extensions/__internal
I0606 20:35:39.440216       1 genericapiserver.go:82] Adding storage destination for group autoscaling
I0606 20:35:39.440221       1 server.go:352] Configuring batch/v1 storage destination
I0606 20:35:39.440225       1 server.go:366] Using batch/v1 for batch group storage version
I0606 20:35:39.440228       1 server.go:112] constructing etcd storage interface.
  sv: batch/v1
  mv: extensions/__internal
I0606 20:35:39.440254       1 genericapiserver.go:82] Adding storage destination for group batch
I0606 20:35:39.440631       1 genericapiserver.go:393] Node port range unspecified. Defaulting to 30000-32767.
[restful] 2016/06/06 20:35:39 log.go:30: [restful/swagger] listing is available at https://172.15.0.21:443/swaggerapi/
[restful] 2016/06/06 20:35:39 log.go:30: [restful/swagger] https://172.15.0.21:443/swaggerui/ is mapped to folder /swagger-ui/
I0606 20:35:39.755027       1 genericapiserver.go:692] Serving securely on 0.0.0.0:443
I0606 20:35:39.755048       1 genericapiserver.go:734] Serving insecurely on 127.0.0.1:8080
E0606 20:35:40.019931       1 genericapiserver.go:716] Unable to listen for secure (listen tcp 0.0.0.0:443: bind: address already in use); will try again.
```

kubelet Docker logs

```
E0606 22:03:13.811908    1841 event.go:202] Unable to write event: 'dial tcp 172.15.0.21:443: connection refused' (may retry after sleeping)
W0606 22:03:14.299181    1841 manager.go:408] Failed to update status for pod "_()": Get https://172.15.0.21:443/api/v1/namespaces/kube-system/pods/kube-apiserver-6taow: dial tcp 172.15.0.21:443: connection refused
W0606 22:03:14.299421    1841 manager.go:408] Failed to update status for pod "_()": Get https://172.15.0.21:443/api/v1/namespaces/kube-system/pods/kube-proxy-sbzwr: dial tcp 172.15.0.21:443: connection refused
W0606 22:03:14.299602    1841 manager.go:408] Failed to update status for pod "_()": Get https://172.15.0.21:443/api/v1/namespaces/kube-system/pods/kubelet-pipaa: dial tcp 172.15.0.21:443: connection refused
```

Host kubelet

```
# /etc/systemd/system/kubelet.service
[Unit]
Description=Kubelet via Hyperkube ACI
Requires=flanneld.service
After=flanneld.service
[Service]
Environment=KUBELET_ACI=quay.io/aaron_levy/hyperkube
Environment=KUBELET_VERSION=v1.2.2_runonce.0
ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --runonce \
  --runonce-timeout=60s \
  --api-servers=https://172.15.0.21:443 \
  --kubeconfig=/etc/kubernetes/kubeconfig \
  --lock-file=/var/run/lock/kubelet.lock \
  --allow-privileged \
  --hostname-override=172.15.0.21 \
  --node-labels=master=true \
  --minimum-container-ttl-duration=3m0s \
  --cluster_dns=10.3.0.10 \
  --cluster_domain=cluster.local
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target
```

Generated `apiserver` manifest

```
apiVersion: "extensions/v1beta1"
kind: DaemonSet
metadata:
  name: kube-apiserver
  namespace: kube-system
  labels:
    k8s-app: kube-apiserver
    version: v1.2.2_coreos.0
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-apiserver
        version: v1.2.2_coreos.0
    spec:
      nodeSelector:
        master: "true"
      hostNetwork: true
      containers:
      - name: kube-apiserver
        image: quay.io/peanutbutter/hyperkube:v1.2.4_inotify.3
        command:
        - /hyperkube
        - apiserver
        - --bind-address=0.0.0.0
        - --secure-port=443
        - --insecure-port=8080
        - --advertise-address=$(MY_POD_IP)
        - --etcd-servers=http://172.15.0.21:2379
        - --allow-privileged=true
        - --service-cluster-ip-range=10.3.0.0/24
        - --admission-control=NamespaceLifecycle,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
        - --tls-cert-file=/etc/kubernetes/secrets/apiserver.crt
        - --tls-private-key-file=/etc/kubernetes/secrets/apiserver.key
        - --service-account-key-file=/etc/kubernetes/secrets/service-account.pub
        - --client-ca-file=/etc/kubernetes/secrets/ca.crt
        env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 443
          hostPort: 443
          name: https
        - containerPort: 8080
          hostPort: 8080
          name: local
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ssl-certs-host
          readOnly: true
        - mountPath: /etc/kubernetes/secrets
          name: secrets
          readOnly: true
      volumes:
      - name: ssl-certs-host
        hostPath:
          path: /usr/share/ca-certificates
      - name: secrets
        secret:
          secretName: kube-apiserver
```

**Comment by aaronlevy** [comment]
@dghubble Can you try increasing the logs on the api-server (`--v10`)?

Based on that retry message, the apiserver should not be exiting (just in a loop which tries to bind on that interface):

https://github.com/kubernetes/kubernetes/blob/v1.2.4/pkg/genericapiserver/genericapiserver.go#L716

If it does exit, and there's only one api-server (which is true for now), this could lead to a race... but kubelet should even be able to recover locally from that (loss of api-server after pod has been scheduled).

**Comment by aaronlevy** [comment]
Also, are you giving it any time to recover? The sync loop may take a bit (but again ... it shouldn't be exiting based on that log message anyway).

**Comment by dghubble** [comment]
It ran for a few hours without recovering. I'll add the verbosity flag in the future when I have time to provision a bunch of clusters.

**Comment by dghubble** [comment]
These cluster crashes still happen with dee39f86de3d84c5e9f88e7ab977708c86c95ced in regular use, typically within the first few minutes of starting generated pods. Validating by running a vagrant VM and checking the desired containers will mask the unreliability of keeping the cluster running.

This is especially hard to check because docker logs are cleared within a few minutes after cluster crash?  As far as causes, it is hard to separate the noise of the "regular" failures from what matters without more knowledge of Kubernetes. I've seen the api port binding error, I've seen TLS handshakes work for a time and then seemingly start failing, etc. In one (mis-)configuration (unrelated misconfig), a kube-proxy could not find the /etc/kubernetes/kubeconfig (was playing with mount from other locations, bad idea) - surprisingly the inability to start the proxy seemed to precipitate the cluster crash, though apiserver was running.

I've tested various bootkube executables and generated files. But there is too much going on here for me to make sense of or spend more time on right now. It may be advisable for `bootkube start` wait until generated pod manifests are running successfully for a time before existing.

**Comment by aaronlevy** [comment]
> Validating by running a vagrant VM and checking the desired containers will mask the unreliability of keeping the cluster running.

Can you provide more details? Not really sure what you mean here.

> This is especially hard to check because docker logs are cleared within a few minutes after cluster crash

The container GC should be configurable if you want it to wait longer:
https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L190
https://github.com/coreos/bootkube/blob/master/pkg/asset/templates/kubelet.yaml#L34

> I've seen TLS handshakes work for a time and then seemingly start failing.
> [...] a kube-proxy could not find the /etc/kubernetes/kubeconfig

These both sound like mis-configuration of the templates. Do you have something that is reproducible? If so we can go over the configs for potential problems.

>  It may be advisable for bootkube start wait until generated pod manifests are running successfully for a time before existing.

Possibly, but i'm not sure "wait longer" is the right answer here. If components are unable to start due to misconfiguration, they're never going to start no matter how long we wait. And if it's a race - we should identify it .. waiting longer likely won't help the issue.

Unfortunately, I've still not run into this issue (in any recent iteration of this tool).

**Comment by dghubble** [comment]
> Can you provide more details? Not really sure what you mean here.

I mean that typically, I'll see `kubectl` commands succeed for a time and return nodes and show containers starting and otherwise seem ok. Over the next few minutes, the cluster can become inaccessible. Spinning up a vagrant VM and checking `kube-*` pods are running once and then destroying it may miss something happening on real clusters. I'd leave it running for a bit, launch some pods, etc.

Ok, increasing the GC period is a change on the deploys to improve debuggability for when this happens.

> Do you have something that is reproducible?

No, its random. It still occurs with updates https://github.com/coreos/coreos-baremetal/pull/237 and through an internal workflow (I'll link you offline). The hack examples work with vagrant/virtualbox so at some point I may need to try to reproduce using your flow or have one of you using Linux verify in the libvirt or bare metal flow.

> These both sound like mis-configuration of the templates.

Yes, it was an unrelated mounting experiment I was doing. The surprising bit is that repeated failures to launch the proxy (in that case, expected) seemed to precipitate the apiserver and cluster crash. This could be yet another red herring though.

**Comment by aaronlevy** [comment]
We are testing more than just spinning up / immediately shutting down. See conformance tests:
https://github.com/coreos/bootkube#conformance-tests

Also, haven't run into this issue against GCE clusters: https://github.com/coreos/bootkube/pull/55

Now somewhat related, if you do lose all api-servers, there isn't currently a recovery method for this. The options currently are: multiple apiservers (must be load-balanced or behind DNS) -- or checkpointing the api-server pod locally, which is what @derekparker has been working on as an interim solution: https://github.com/coreos/bootkube/pull/50

But this still doesn't have to do with bootstrapping per-se ... your apiservers shouldn't just immediately fail. But reboots, or docker failing, etc could cause the self-hosted api-server to not recover (assuming a single copy). Along those lines -- could it be that your nodes are rebooting during a CoreOS update right after first boot?

**Comment by dghubble** [comment]
Auto-updates would cause the apiserver to fail, but so far that hasn't been the cause. As soon as I see kubectl commands failing I connect and check `docker ps -a` to find a bunch of exited `kube-*` containers. If the clusters lasted more than a few minutes, the master node would eventually find and download a CoreOS update now that there is a newer alpha than 1053.0.0, but we don't get that far.

**Comment by philips** [comment]
@dghubble Can you "kill -SIGQUIT" the process so we know what go routine it is hung on?

**Comment by dghubble** [comment]
As of a few weeks ago, we're able to pin both the rendering and on-host bootkube to matching tagged releases every time. I haven't seen this flake since doing so. I'll re-open if it crops up.
