### ISSUE TITLE
Git Tag release commits for simpler checkout/signing

### ISSUE THREAD

**Issue by dghubble** [coreos/bootkube#76]

**Comment by aaronlevy** [comment]
Hmm. Was one of the releases built incorrectly? Releases are tagged (the release build shouldn't even work on a non-tagged ref)

**Comment by dghubble** [comment]
Perhaps they just aren't pushed to origin.

    git push origin --tags

**Comment by aaronlevy** [comment]
definitely pushed: https://github.com/coreos/bootkube/tree/v0.1.1
