### ISSUE TITLE
Vagrant examples using out-dated user-data.sample

### ISSUE THREAD

**Issue by chancez** [coreos/bootkube#79]
The `user-data.sample` file within the `hack/` directory for Vagrant isn't up to date it seems. It's missing some stuff relating to the checkpointer's `checkpoint-secrets` directory, and im not sure what else, but the checkpointer isn't running when I attempt to use Vagrant.

**Comment by derekparker** [comment]
Can you update with what hack cluster you're using (`single-node` or `multi-node`) and logs from kubelet trying to start the pod, or logs from the pod starting or something? I've run on `single-node` and `multi-node` several times without issue with the checkpointer.

Also, looking at https://github.com/coreos/bootkube/blob/master/hack/multi-node/user-data.sample#L32 it seems the dir is being created by that unit.

**Comment by derekparker** [comment]
@chancez also, be sure you  `rm -rf $dir/cluster` in case you had old rendered cluster assets. The script does not remove and recreate that dir every run.

**Comment by chancez** [comment]
Oh whoops, I didn't have that in the README I was referencing. I had an open vim buffer referring to the old README before I ran `git pull` so I didn't notice that addition.
